const express = require('express');
const cors = require('cors');
const { getConnection } = require('./db');

const app = express();
app.use(cors());
app.use('/images', express.static(__dirname + '/images'));

async function dutyExists(connection, dutyDate) {
    const result = await connection.execute(
        `SELECT COUNT(*) AS CNT
         FROM duty_schedule
         WHERE TRUNC(duty_date) = TRUNC(:dutyDate)`,
        { dutyDate }
    );
    return result.rows[0].CNT > 0;
}
async function autoGenerateDuty(connection, dutyDate) {

    const dutyDay = dutyDate
        .toLocaleDateString('en-US', { weekday: 'long' })
        .toUpperCase();

    const officers = [1001,1002,1003,1004,1005,1006,1007,1008];

    const duties = [
        // ACTIVE
        ['MAIN_GATE','DAY','N', officers[0]],
        ['MAIN_GATE','NIGHT','N', officers[1]],
        ['HQ_GATE','DAY','N', officers[2]],
        ['HQ_GATE','NIGHT','N', officers[3]],
        // STANDBY
        ['MAIN_GATE','DAY','Y', officers[4]],
        ['MAIN_GATE','NIGHT','Y', officers[5]],
        ['HQ_GATE','DAY','Y', officers[6]],
        ['HQ_GATE','NIGHT','Y', officers[7]]
    ];

    for (const d of duties) {
        await connection.execute(
            `
            INSERT INTO duty_schedule
            (duty_date, duty_day, duty_point, shift, standby_flag, personal_number)
            VALUES (:dateVal, :dutyDay, :point, :shiftVal, :standby, :pn)
            `,
            {
                dateVal: dutyDate,
                dutyDay: dutyDay,
                point: d[0],
                shiftVal: d[1],
                standby: d[2],
                pn: d[3]
            }
        );
    }

    await connection.commit();
}


// ROOT ROUTE
app.get('/', (req, res) => {
    res.send('DRDL Duty API is running');
});

// TEST API
app.get('/duty-data', async (req, res) => {
    let connection;
    try {
        connection = await getConnection();

        const result = await connection.execute(
            `SELECT d.duty_date,
       d.duty_day,
       d.duty_point,
       d.shift,
       d.standby_flag,
       o.officer_name,
       o.gender
FROM duty_schedule d
JOIN officer_master o

               ON d.personal_number = o.personal_number
             ORDER BY d.duty_date, d.standby_flag, d.duty_point, d.shift`
        );

        res.json(result.rows);
    } catch (err) {
        console.error(err);
        res.status(500).send('Database error');
    } finally {
        if (connection) {
            try {
                await connection.close();
            } catch (err) {
                console.error(err);
            }
        }
    }
});

app.listen(4000, () => {
    console.log('Server running on http://localhost:4000');
});
function getNextWorkingDay(date) {
    const next = new Date(date);
    next.setDate(next.getDate() + 1);

    // 0 = Sunday, 6 = Saturday
    if (next.getDay() === 6) { // Saturday
        next.setDate(next.getDate() + 2);
    } else if (next.getDay() === 0) { // Sunday
        next.setDate(next.getDate() + 1);
    }
    return next;
}

app.get('/duty-carousel', async (req, res) => {
    let connection;
    try {
        const today = new Date();
        const nextDay = getNextWorkingDay(today);

        connection = await getConnection();

        // ✅ AUTO-GENERATE (JS logic – NOT SQL)
        if (!(await dutyExists(connection, today))) {
            await autoGenerateDuty(connection, today);
        }

        if (!(await dutyExists(connection, nextDay))) {
            await autoGenerateDuty(connection, nextDay);
        }

        // ✅ FETCH DATA
        const result = await connection.execute(
            `
            SELECT d.duty_date,
                   d.duty_day,
                   d.duty_point,
                   d.shift,
                   d.standby_flag,
                   o.officer_name,
                   o.gender
            FROM duty_schedule d
            JOIN officer_master o
              ON d.personal_number = o.personal_number
            WHERE TRUNC(d.duty_date) IN (TRUNC(:today), TRUNC(:nextDay))
            ORDER BY d.duty_date, d.standby_flag, d.duty_point, d.shift
            `,
            {
                today: today,
                nextDay: nextDay
            }
        );

        res.json(result.rows);

    } catch (err) {
        console.error(err);
        res.status(500).send('Database error');
    } finally {
        if (connection) {
            await connection.close();
        }
    }
});
